### PR TITLE
fix: use panel language by default, make not required, add geolocate

### LINKED ISSUE #260: "Language" Field of User Creation
Currently, when creating a User in the Admin View, you get these fields (Yes, this is German, I apologize.):

Image

The point is there is a required field in the bottom right of the first panel. On the screenshot it is reading "Sprache", but it's basically the Language Field.

However, it has two issues:
- It is auto populated with English Instead of the Panel's Default Language.
- It's required.

These are simple things that in my opinion are just a bad inconvenience. It should either be empty and not required or populated with the default language set in the settings.

### PR DESCRIPTION
**Pull request by jasonzli-DEV**
Fixes #260 

This pr makes the user creation ui autofill the language form with the panel's default language, makes it not required, and adds a geolocate option.

### CODE REVIEW

File: app/Http/Middleware/LanguageMiddleware.php [hunk 1]
```diff
@@ -29,7 +29,12 @@ public function handle(Request $request, \Closure $next): mixed
         $user = $request->user();
 
         if ($user !== null) {
-            $locale = $user->language;
+            if ($user->language === 'geo') {
+                $defaultLocale = $this->settings->get('settings::app:locale', config('app.locale', 'en'));
+                $locale = $this->resolveGeoLocale($request, $defaultLocale);
+            } else {
+                $locale = $user->language;
+            }
```
Comment (GunnableScum) [inline app/Http/Middleware/LanguageMiddleware.php:37]: Using the Geolocate Option and then logging in with a Local IP results in No language.

Image

**Review by GunnableScum — CHANGES_REQUESTED** [review]
Great start, small issue.

**Comment by GunnableScum** [comment]
> Hmm ok. I'll take a look when I'm free. Thanks!

Hold on, this might've been my fault.

**Comment by jasonzli-DEV** [comment]
Oh! Ok, no problem 😅

**Comment by GunnableScum** [comment]
Alright nevermind, just tested this again on another fresh user and this happens.
image

**Comment by GunnableScum** [comment]
But hey, something good out of this: This can help me find untranslated strings for #244.

**Comment by jasonzli-DEV** [comment]
Oh yeah! You can easily see everything that's not translataed. Although I'd have to figure out how you did that.

**Comment by GunnableScum** [comment]
> Oh yeah! You can easily see everything that's not translataed. Although I'd have to figure out how you did that.

Since the language indicator shows no flag, I'm sure in the database the user has a NULL language, which I guess can show me everywhere the trans function is not used. I'll quickly check the DB if that's true.

**Comment by jasonzli-DEV** [comment]
That makes sense, should the database auto correct to the default language on null or should the cause for this be further invesigated?

**Comment by GunnableScum** [comment]
Actually, it's *not* null. It just sticks to "geo".

image

**Comment by GunnableScum** [comment]
So, I guess there's your problem.

**Comment by jasonzli-DEV** [comment]
Oh, ok. Let me open up my codespace and take a look.

**Comment by GunnableScum** [comment]
Good luck!

**Comment by jasonzli-DEV** [comment]
That should do it!

**Comment by GunnableScum** [comment]
I'll have a look at this (and if you decide to in the meantime work on your other PRs) tomorrow. It's 10pm over here and I have school to go to tomorrow. But if anybody else in @reviactyl/project-developers feels like it, they can test and review this in my place or wait until I get back tomorrow.

**Comment by jasonzli-DEV** [comment]
Alright, thanks so much! Have a good night!

**Comment by GunnableScum** [comment]
Alright, I'm now available, testing this now.

**Review by GunnableScum — APPROVED** [review]
# Testing Screenshot

Image

Works perfectly. I suppose a future change would be that when the user first logs in when the value is "geo" that it'd be changed to whatever is decided upon. (i.e. German since geo is enabled and I'm connecting locally which results in Panel Default Fallback)

Regardless of that, works perfectly. Merging!
